void reset_to_98(int *n);
void swap_int(int *a, int *b);
int _strlen(char *s);
void _puts(char *str);
void print_rev(char *s);
int main(void);
int _putchar(char c);
void rev_string(char *s);
void puts2(char *str);
void puts_half(char *str);
char *_strcpy(char *dest, char *src);
int _atoi(char *s);
char *_strcat(char *dest, char *src);
int main(void);
char *_strncpy(char *dest, char *src, int n);
char *cap_string(char *a);
char *_memset(char *s, char b, unsigned int n);
char *_strpbrk(char *s, char *accept);
